apiVersion: esx.vmware.com/v1alpha1
kind: HostConfiguration
metadata:
  name: keswick-host-config
  namespace: esx-system
spec:
  layertype: Incremental
  profile: |
    {
      "esx": {
        "welcome_message": {
          "message": \"{align:left}{color:white} \\n\\n\\n\\n\\t XiaoVMware\\n\\n\\t4 X Intel(R) Xeon(R) Gold 5120 CPU @ 2.20GHz\\n\\n\\t{memory} Memory\\n\\n\\n\\n\\tVendor: VMware, Inc.\\n\\n\\t
          }
        "system": {
          "system_time": {
            "enabled": true,
            "protocol": "NTP",
            "ntp_config": {
              "server": [{
                  "hostname": "0.pool.ntp.org",
                  "command": "SERVER"
                },
                {
                  "hostname": "1.pool.ntp.org",
                  "command": "SERVER"
                }
              ]
            }
          }
        }
      }
    }
