apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachineClass
metadata:
  name: best-effort-ec-small2
  # No resource requests/reservations.
  # Memory overcommit possible.
spec:
  # VM operator controller name for VirtualMachine class
  # is different so addition of controllerName attr with invalid
  # value makes vm operator ignore this VM CRD instance.
  # This is majorly done because vm operator doesn't have all the
  # needed capabilities to deploy ec worker vm.
  controllerName: vmoperator.vmware.com/ecworker
  hardware:
    cpus: 4
    memory: 8Gi
---
apiVersion: v1
kind: Namespace
metadata:
  name: ec-system
---
apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  name: ec-worker
  namespace: ec-system
spec:
  className: best-effort-ec-small2
  imageName: ec-wrkr.ova
  powerState: poweredOn
  networkInterfaces:
  - networkName: "VMNetwork3"
    ethernetCardType: "vmxnet3"
  networkInterfaces:
  - networkName: "VMNetwork4"
    ethernetCardType: "vmxnet3"
  vmMetadata:
    transport: CloudInit
    configMapName: worker-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-config
  namespace: ec-system
data:
  networkconfig: |
        version: 2
        ethernets:
            eth0:
                dhcp: "false"
                addresses:
                    - 172.16.202.100/24
                nameservers:
                    addresses:
                        - 1.1.1.1
                routes:
                    - to: 0.0.0.0/0
                      via: 172.16.202.1
